version: '3.8'

services:
 minio:
   container_name: minio_server
   image: minio/minio:latest
   volumes:
     - ./minio/data:/data
   ports:
     - "9000:9000"
     - "9001:9001"
   command: server /data --console-address ":9001"
